theme: jekyll-theme-cayman
google_analytics: 
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VY4PB32SPK"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VY4PB32SPK');
</script>